### ISSUE TITLE
Include X-Axis for Visit #

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/ae-timelines#10]
-Include x-axis for visit #, not study day
o   Match to screening, baseline, week 1, etc.
o   Jack will provide information from protocols

**Comment by brittsikora** [comment]
Related to Jack's new request for adding details to the x-axis, so he can identify if it is measuring study visit, day, etc. A note for an x-axis filter has been added to Ryan's SE migration spreadsheet (under AE Timeline) for future reference.

**Comment by samussiah** [comment]
Britt, I'm not exactly sure how to implement this request.  Sounds like Jack is suggesting we label the x-axis based on the study's schedule of events, e.g. days -14 through -1 map to 'Screening', day 0 maps to 'Visit 0', etc.  I'd like to see an example dataset before I get started.

**Comment by brittsikora** [comment]
Let's discuss this with @jwildfire when he returns and he might be able to provide some guidance

**Comment by samussiah** [comment]
Just throwing a couple ideas out there:

- Shade the chart background based on what study visit a study day maps to.
-- This would require a uniform study day to study visit mapping and the schedule of events dataset.
- Add a second x-axis, each tick label of which spans a varying number of study days.
-- Single day visits are going to look cramped, and this'll have the same requirements as above.
- Add study visit to the tooltips and maybe the details listing.
-- This would be extremely simple but require reviewing tooltips.

**Comment by jwildfire** [comment]
@samussiah I think your third option is the best place to start. Just add the study visit name ("Screening") to the tooltip. We'll also need to make sure that variable gets added as part of the variable mapping in the [chart-foundry build process](https://github.com/RhoInc/webcharts-wrapper-boilerplate/wiki/Wrapper-Creation-Workflow#phase-2---chartfoundry-renderer). 

The main limitation is that we can't really have a categorical x-axis here. The other option is to allow the user to toggle between study visit (numeric) and study day (also numeric) like we do in the [outlier explorer](http://bl.ocks.org/jwildfire/5633141e5b73e8521b719ac0a2f8d24f), but I'm just not sure that is worth it ...

**Comment by jwildfire** [comment]
Let's resolve this (one way or the other) in v1.3.0

**Comment by samussiah** [comment]
Modified tooltips to conditionally append study visit when user specified `vis_col`, which defaults to null.

**Comment by jwildfire** [comment]
@samussiah After the code review, I think we should just take this out for now, close the issue as "won't fix" and see if it gets requested again later. If we're going to add a third data stream, there are more elegant ways to show when visits occur in relation to the AEs. 

The most obvious way is just to append another data set that is one record per person per visit and just draw an additional mark for visits. We've done this in a few internal timelines that we can dig up if we decide to pursue this.

**Comment by jwildfire** [comment]
tagged as wontfix and closed.
