### ISSUE TITLE
Show # of Enrolled/Randomized Participants

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/ae-timelines#15]
Not sure the best way to handle this, but it would be good to have the number of relevant study participants shown somewhere on the chart. Maybe add a footnote for "X of X participants shown in this view"

**Comment by jwildfire** [comment]
Implemented in v1.2.0. See [update-subject-count.js](https://github.com/RhoInc/ae-timelines/blob/261259d011532c4d12b5a753fecf190283b93d62/src/util/update-subject-count.js)
