### ISSUE TITLE
Show Serious adverse events using a different mark.

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/ae-timelines#19]
Use an "X" or an "S" instead of a circle. 

See https://github.com/RhoInc/aeexplorer/issues/3 for original request.

**Comment by samussiah** [comment]
I've added a second set of lines and marks for just SAEs.  The lines are thinner and black while the circles have a larger radius and a black stroke.

**Comment by jwildfire** [comment]
I like the direction this is going, but might tweak a few details. 

How about using the fill instead of the stroke to indicated seriousness. fill-opacity:0 for non serious. fill-opacity:1 for serious? Maybe change the stroke-width to be a bit smaller as well? Then add a footnote that say "Filled circles indicate serious adverse events"

**Comment by jwildfire** [comment]
Also, the "end date" circles should probably just be hidden. I just created issue #20 for that.

**Comment by samussiah** [comment]
I dig it.  Will test out on branch SAEs.

**Comment by samussiah** [comment]
Implemented in v1.3.0.  Went with the black outline and added a legend item.
