### ISSUE TITLE
Don't show circle for the end of the AE

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/ae-timelines#20]
Just show a circle for the start date, and then a line that goes to the end date. No circle needed at the end date.

**Comment by samussiah** [comment]
Implemented in v1.3.0 by filtering out `wc_category === config.endy_col`.

**Comment by jwildfire** [comment]
[Here](https://github.com/RhoInc/ae-timelines/commit/c71ed0cf8917e337eb85174d5a7be21ae6417bf1#diff-f77024d32bebd94e5bb76705cc90f855R159), yes? Haven't tested, but it looks good to me.

**Comment by samussiah** [comment]
Yup, will have a gist shortly.

**Comment by jwildfire** [comment]
Implemented in #22
