### ISSUE TITLE
Add participant status filter

### ISSUE THREAD

**Issue by rtbailey** [RhoInc/ae-timelines#21]
For example, the ability to filter on "Active" vs. "Discontinued"

**Comment by samussiah** [comment]
We could use RFENDTC (Subject Reference End Date/Time) from the DM domain as the basis for a participant flag.

**Comment by samussiah** [comment]
Implemented in v1.3.0 by requiring RFENDTC from the DM domain.  This date will be null for participants who have not completed the study.  However I'm not sure how screen failures will be categorized.

**Comment by jwildfire** [comment]
Hmm, I'm on the fence about this implementation. It's nice to have this built in, but also limits the generalizability a bit. Finally, I'm concerned about adding new required columns, are we going to run in to problems with teams that don't have the RFENDTC variable derived as part of their standard workflow? 

I'm actually thinking it might make more sense to take a _very_ generic approach here, and require the user to provide a standard status variable for each participant if they want this filter (status = "active" or "discontinued" etc.)

@rtbailey and @srosanba I'd be interested to get your input on this.

**Comment by jwildfire** [comment]
Note the contrast here: https://github.com/RhoInc/safety-histogram/issues/23
