### ISSUE TITLE
Address Backwards compatability in next release

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/ae-timelines#24]
As noted [here](https://github.com/RhoInc/ae-timelines/pull/22#discussion-diff-94696940R11), I think the addition of a new required variable (`ser_col: 'AESER'`) breaks backwards compatibility in the upcoming release. I see 2 options: 

1. Just call this release v2.0.0 instead of v1.3.0 or ..
2. Change the default for `ser_col` to `null` and update the renderer to handle that.

I'm leaning towards option 1 ... @samussiah @brittsikora thoughts? @rtbailey any opinion for ops?

**Comment by samussiah** [comment]
SAEs are a big deal to investigators and pretty much universally captured.  I vote break backwards compatibility.

**Comment by jwildfire** [comment]
OK with me. Next release will be v2.0.0.

**Comment by jwildfire** [comment]
Went ahead and updated in #22
