### ISSUE TITLE
Rework highlight functionality to use extra marks

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/ae-timelines#26]
See outlier explorer for similar implementation.

**Comment by samussiah** [comment]
[default](http://bl.ocks.org/samussiah/raw/0917733a1fda88b274bb482103c84e22/)
[custom](http://bl.ocks.org/samussiah/raw/56ed5bd11998cc8867876c8843db815e/)

**Comment by jwildfire** [comment]
Closed in #27
