### ISSUE TITLE
Use config.color_dom to define color domain.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/ae-timelines#32]
like set it to `config.colors.values`

# Test notes
* Internal codebase changes only, no need for feature testing.

**Comment by jwildfire** [comment]
How is this different from the current behaviour? Is this a bug?

**Comment by samussiah** [comment]
Only categories existent in the data appear in the legend if unspecified.

**Comment by emmorris** [comment]
@samussiah , how should this one be tested?

**Comment by samussiah** [comment]
No need to feature test this one.
