### ISSUE TITLE
Handle the use case where only a single point is drawn and the x-axis doesn't have a single tick.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/ae-timelines#33]
![image](https://user-images.githubusercontent.com/5428548/31056221-2ce65f52-a69c-11e7-9ff1-04cc9279e356.png)

**Comment by jwildfire** [comment]
I wonder if this is better addressed long term as a webcharts issue. Current behavior when there is only a single value x, just sets the domain to [x,x], which is no good.

**Comment by emmorris** [comment]
We are doing this in the Shift Plot as well

**Comment by emmorris** [comment]
Handling this in Webcharts #44
