### ISSUE TITLE
Table shouldn't be shown on initial load. 

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/ae-timelines#39]
Bug introduced with webcharts v1.9

**Comment by jwildfire** [comment]
Test Notes: Confirm that no table appears until an x-axis id is clicked.

**Comment by dschwentker** [comment]
Tested and confirmed that the table is no longer appearing at the bottom of the initial renderer page in all browsers in v2.0.4-dev - table now only appears after clicking on a participant id in the x-axis.
