### ISSUE TITLE
Don't show 'NA's from placeholder rows in filters

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/ae-timelines#41]
See project 173 for example. 

Implement a placeholder_row variable like in ae explorer? 

# Test notes
* Verify that records without a value of adverse event verbatim term (variable: _AETERM_, setting: `term_col`) or with a non-integer adverse event start day (variable: _ASTDY_, setting: `stdy_col`) are not plotted.
  * To clarify, these records _should_ represent placeholder rows, i.e. rows that represent participants without any adverse events.  Find one of these records in CAT and verify that the associated participant ID appears in neither the chart nor the _Participant Identifier_ dropdown.

**Comment by brittsikora** [comment]
Do you mean project 273?
